### ISSUE TITLE
Feature Request: Fair semaphore implementation

### ISSUE THREAD

**Issue by alexf-bond** [ionelmc/python-redis-lock#104]
https://redis.com/ebook/part-2-core-concepts/chapter-6-application-components-in-redis/6-3-counting-semaphores/6-3-2-fair-semaphores/

Would be a nice addition to add an optional fairness to lock acquisition model such that lock requests can happen in the order in which they're requested.  This would prevent the case where:

Process 1 -> Acquires Lock A
Process 2 -> Blocks Locking A
Process 1 -> Releases Lock A
Process 1 -> Relocks A (prior to process 2)
Process 1 -> Releases Lock A
Process 2 -> Acquires Lock A
Process 2 -> Release Lock A

**Comment by ionelmc** [comment]
What is a pod, and more importantly what is msg in the context of this project? I don't wanna be abrasive but are you sure you meant to make this feature request in *this* project, instead of a lock implementation in a different project? 

The `while busy:` loop in this project is not a spinloop as there is a blocking operation inside (that `blpop` in the middle will wait for a different client to release the lock).

**Comment by alexf-bond** [comment]
No abrasiveness taken :).  Pod (kubernetes) / process / thread etc, just a set of distributed processes that are attempting to potentially lock on the same name. My request is in this repo just with the enhancement of "fairness" in that the locks are always acquired in the order that they're requested.  

Potentially:
- Add a `fair: bool` to the existing `class **Lock(object):` class which accounts for it
- Add `class FairLock(object):` [similar to how the fair boolean works in the Java reentrant lock](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/ReentrantLock.html).

**Comment by ionelmc** [comment]
Yes but what exactly should be changed? In my mind the implementation already has "fairness".

**Comment by ionelmc** [comment]
Am I missing something? I see this right here https://redis.io/commands/blpop/

> If multiple clients are blocked for the same key, **the first client to be served is the one that was waiting for more time (the first that blocked for the key)**. Once a client is unblocked it does not retain any priority, when it blocks again with the next call to BLPOP it will be served accordingly to the number of clients already blocked for the same key, that will all be served before it (from the first to the last that blocked).
