### ISSUE TITLE
A question about recursive lock

### ISSUE THREAD

**Issue by yuzaoyah** [ionelmc/python-redis-lock#118]
Hello. Does it now support recursive lock? Or is there a plan to implement it? If neither of them，could you tell me how to implement it using python-redis-lock? Tks.

**Comment by ionelmc** [comment]
Recursive as in a lock that has an internal counter and only actually releases when the counter is down to 0 (released as many times as it acquired)? No support for that, but you can implement that yourself, it's just a counter.

**Comment by yuzaoyah** [comment]
> Recursive as in a lock that has an internal counter and only actually releases when the counter is down to 0 (released as many times as it acquired)? No support for that, but you can implement that yourself, it's just a counter.
Ok, tks.
