### ISSUE TITLE
The orphan signal list bug

### ISSUE THREAD

**Issue by Suor** [ionelmc/python-redis-lock#14]
Situation:
1. Process A acquires lock.
2. Process B blocks.
3. Process B unblocks cause of expire (or failure).
4. Process A releases lock and pushes to signal list.

Now system is in a broken state, cause if 2 processes come again:
1. Process A acquires lock.
2. Process B fails to `set nx`, but doesn't block cause of orphan element in a signal list.

This could be mitigated if `set nx` command is wrapped into lua script, which deletes signal list. Rule: signal list should be empty upon acquire.

**Comment by ionelmc** [comment]
Hmmmm, wouldn't it be a better solution to cleanup the signal list on acquire? That would "cleanup" things even when the datastructures are messed up.

**Comment by Suor** [comment]
It's exactly the thing that I proposed. I should note that for this to be reliable "acquire + list cleanup" thing should be atomic, so this is either lua script or transaction.

**Comment by ionelmc** [comment]
Aaah, now I fully get it :) Yes, very good idea, good catch. Did you test this or just review the code?

**Comment by Suor** [comment]
Just reviewed the code.

**Comment by Suor** [comment]
Lua is probably an overkill, [this thing](https://redis-py.readthedocs.org/en/latest/#redis.Redis.pipeline) will do the job.

**Comment by ionelmc** [comment]
Ok, so I've taken some more time to look at this.

The unlock script does check if it "owns" the lock (`if redis.call("get", KEYS[1]) == ARGV[1] then`) - and if not, it doesn't do anything (like pushing signals).

There is a problem tho with the acquire (it doesn't set the signal id in the `lock:foobar` string key, so the unlock can push a bogus signal).

**Comment by ionelmc** [comment]
Another thing, if the lock expired then `redis.call("get", KEYS[1]) == ARGV[1]` still won't be true (cause the key isn't there anymore).

**Comment by ionelmc** [comment]
I think this is not an issue at all. The acquire protocol will consume all the signals, and the release protocol checks the that the ID of the lock holder matches whoever is releasing.

Let me know if you still think there's some problem.
