### ISSUE TITLE
redis-lock does not delete lock-signals

### ISSUE THREAD

**Issue by liorchen** [ionelmc/python-redis-lock#17]
I'm using this library against a massive load of users.
I can see that the library doesn't clean up lock-signal:xxx items from Redis.

Am I missing something? when should be cleaned exactly? cause my Redis's memory will eventually be over..

Thx
Lior.

**Comment by ionelmc** [comment]
Hey, Can you describe the conditions under which that happens? Some sample code that reproduces the issue would be ideal. At the very least you should give some details about how many items you have there and how often they accumulate.

**Comment by liorchen** [comment]
Ok
So I have a message object that is queued by my application server and once a client that is targeted to that object connects to the web server, that web server sends the message to the client.
I'm able to reproduce this issue even when having a small number of clients connected to my servers (at staging environment).

I use redis lock in my web-server just before sending a message to a client.
My usage with the redis-lock is pretty simple:
```
with Lock(redis_conn, str(msg.id)):
    #update the message as sent so other webservers will never get it
```
Any idea why the lock-signal is still there after this code runs?

**Comment by ionelmc** [comment]
So is it correct to assume that you have very many possible `msg.id`? And that's what's making this bad?

This implementation is optimised for cases where you have very few locks and lots and lots of clients using said small set of locks.

AFAIK, there's a builtin lock implementation on the redis-py library (as outlined in https://github.com/ionelmc/python-redis-lock#similar-projects)

**Comment by liorchen** [comment]
Yes, you are right. many possible ```msg.id```. This library's implementation probably does not feet well with my needs.

Thank you, I guess I'll have to use some other implementation.

**Comment by travcunn** [comment]
This caveat should be documented in the README. This implementation also does not meet my needs since I also have many different lock ids. It wasn't until I ran ```echo "KEYS lock*" | redis-cli | wc -l``` that I realized there was going to be a problem.

**Comment by ionelmc** [comment]
I need to do some more research. Maybe it's possible to expire the signal keys somehow ...

**Comment by AndrewPashkin** [comment]
[EXPIRE](http://redis.io/commands/expire) works on lists too, `PUBSLISH`/`SUBSCRIBE` can also be used.
