### ISSUE TITLE
Inconsisten usage of `_held`

### ISSUE THREAD

**Issue by AndreiPashkin** [ionelmc/python-redis-lock#48]
1) [Here](https://github.com/ionelmc/python-redis-lock/blob/0600e0e5e39b1bed4024a28b780696247cb6da40/src/redis_lock/__init__.py#L335) and [here](https://github.com/ionelmc/python-redis-lock/blob/0600e0e5e39b1bed4024a28b780696247cb6da40/src/redis_lock/__init__.py#L341) - duplicate check for case if a lock is already held - additional overhead.
2) [Here](https://github.com/ionelmc/python-redis-lock/blob/0600e0e5e39b1bed4024a28b780696247cb6da40/src/redis_lock/__init__.py#L255) - `_held` is not used, and if not - what is the point of it's existence?
3) [Here](https://github.com/ionelmc/python-redis-lock/blob/0600e0e5e39b1bed4024a28b780696247cb6da40/src/redis_lock/__init__.py#L207) - it is kind of duplicate, since `nx=True` is already ensures, that a lock will not override already held lock. And also it produces additional overhead, making additional call to Redis.

So `_held` produces additional calls to Redis in case of redundant checks or usage of `_held`, because `_held` calls to Redis. And it's just violates Feng Shui rules.

**Comment by ionelmc** [comment]
> 1) Here and here - duplicate check for case if a lock is already held.

Indeed. Will remove that.

> 2) Here - _held is not used, and if not - what is the point of it's existence?

So basically it's just used in `acquire`. Are you proposing to use a script in acquire?

**Comment by AndrewPashkin** [comment]
> So basically it's just used in `acquire`. Are you proposing to use a script in acquire?

If remove `_held` call, `acquire` still won't override already held locks, because of `nx=True`, so call to `_held` is partially redundant. Partially - becasue `nx=True` doesn't match `id`'s.

**Comment by ionelmc** [comment]
Yes but it won't raise proper exception either.

**Comment by AndrewPashkin** [comment]
Yes, but should it?

**Comment by ionelmc** [comment]
Yes, if user makes something bad then error should be raised instead of treating the problem silently.

**Comment by AndrewPashkin** [comment]
Another proposition is to make `_held` public.

**Comment by AndrewPashkin** [comment]
>Yes, if user makes something bad then error should be raised instead of treating the problem silently.

Makes sense.

**Comment by ionelmc** [comment]
> Another proposition is to make _held public.

Hmmm. `threading.Lock` has a method `locked`. I think we can match that.

**Comment by AndrewPashkin** [comment]
>Yes, if user makes something bad then error should be raised instead of treating the problem silently.
By the way - currently - this check is performed only in the beginning, but not in blocked state. Should it throw the error in blocked state?

**Comment by ionelmc** [comment]
Good point. I have to investigate.

**Comment by ionelmc** [comment]
Uh ... well kinda late but: in acquire there is this check:
```python

        if self._held:
            raise AlreadyAcquired("Already acquired from this Lock instance.")

```
So I think all problems are resolved?
