### ISSUE TITLE
References to "spinloop" in the documentation

### ISSUE THREAD

**Issue by todofixthis** [ionelmc/python-redis-lock#52]
In https://python-redis-lock.readthedocs.io/en/latest/readme.html#similar-projects there are several references to "spinloop", but I cannot for the life of me find any resources that define this term.

Is there a more widely-used term that can be substituted for "spinloop"?

**Comment by ionelmc** [comment]
Is this good enough? https://en.wikipedia.org/wiki/Busy_waiting - googling for "spin loop" has that for 1st result ...

Or are you asking for some link in docs?

**Comment by todofixthis** [comment]
Ah.  I searched for "spinloop" (1 word), and didn't get nearly as useful results.

Thanks for the link; after doing a bit of reading, it seems to me like this term actually would be well-understood by someone who is used to working with asynchronous code.
