### ISSUE TITLE
Is this implementation suitable for multiple Redis/Django nodes on Docker Cloud?

### ISSUE THREAD

**Issue by mrmachine** [ionelmc/python-redis-lock#53]
I am deploying a project to Docker Cloud which has a Django WSGI service scaled across multiple containers/nodes and a Redis service which is currently just a single container, but might also be scaled to several across multiple nodes.

Docker Cloud is configured to automatically redeploy when a new image is detected on Docker Hub. So all I need to do is push a commit to my master branch, Travis CI builds a new image, runs tests, pushes the image to Docker Hub, then Docker Cloud redeploys the Django WSGI service.

The Django WSGI service has an entrypoint script that compares the expected vs current migration state by comparing the output of `manage.py migrate --list` which is saved into the image it is built, to the output of `manage.py migrate --list` on the running container against the live database. If the output is different, I am assuming that the live database is behind the image and migrations need to be applied.

What I need to do is ensure that only one of these Django WSGI containers actually tries to apply the migrations, (e.g. whichever container gets to it first - they are all redeployed at the same time), and all the others just wait until the first has finished applying migrations before they continue their startup.

I am currently using `django_redis.cache.RedisCache` as the default cache backend. So I think I could just replace that with your version, `redis_lock.django_cache.RedisCache`, and then in a custom `safe_migrate` management command, do something like:

```
from django.core.cache import cache
from django.core.management.commands.migrate import Command


class Command(Command):
    def handle(self, *args, **kwargs):
        with cache.lock('safe_migrate', expire=60, auto_renewal=True):
            if actual_and_expected_migration_state_are_different():
                super(Command, self).handle(*args, **kwargs)
```

Will this work with a single Redis container and multiple Django WSGI containers across several nodes? And will it continue to work if Redis is also scaled across multiple nodes?

**Comment by ionelmc** [comment]
I think you should not care about the implementation that much - when you switch to a cluster redis deployment you should be able to switch out the lock implementation easily. If not, lets talk about what API differences make it hard.

**Comment by mrmachine** [comment]
Thanks. Going to close this. We're using `python-redis-lock` successfully at the moment.
