### ISSUE TITLE
Could we get a release?

### ISSUE THREAD

**Issue by airhorns** [ionelmc/python-redis-lock#62]
It's super awesome that there is a real, production ready locking primitive ready to go! Thanks for building this. Went to use the `auto_renew` functionality from master in Django and sadly was unable to! Confusingly the commit adding it is actually from before the most recent release, but it was only merged recently. A new release to PyPI would allow us to use it without introducing a git dependency! 

Thanks!

**Comment by airhorns** [comment]
ping @ionelmc anything we can do to help out?

**Comment by ionelmc** [comment]
Nothing besides nagging me. I'm not sarcastic - I often forget that something waiting for release 😀
