### ISSUE TITLE
UnicodeDecodeError when decoding owner_id

### ISSUE THREAD

**Issue by mayli** [ionelmc/python-redis-lock#64]
```
redis_lock/__init__.py", line 219, in get_owner_id
    owner_id = owner_id.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 0: ordinal not in range(128)
```

It seems to be introduced by [this commit](https://github.com/ionelmc/python-redis-lock/commit/0db66094ff470c0f685ce32294d8c8615be069fe), which will crash the new version when trying to acquire an lock holding by the old version.

**Comment by ionelmc** [comment]
Oooof ... so I guess you do rolling upgrades?
