### ISSUE TITLE
Is there another race condition when a lock is released?

### ISSUE THREAD

**Issue by mt3925** [ionelmc/python-redis-lock#71]
https://github.com/ionelmc/python-redis-lock/blob/a30bd138f0f3060cc1f51d6a377b4067fae4dda9/src/redis_lock/__init__.py#L362-L368

As shown above, the step to release the lock is 1. Execute the `UNLOCK` script 2. Execute the `_delete_signal` function.
Consider a situation with two processes:
- Process 1 currently holds a lock.
- process 2 is ready to acquire the lock.

Now, suppose that the following sequence of events unfolds:
- process 2 executes the `SETNX` command to obtain the lock but does not get it.
- Process 1 executes the `UNLOCK` script to release the lock.
- process 1 executes the `_delete_signal` function.
- process 2 executes the `BLPOP` command. It then waits for a timeout to acquire the lock again, and that's the problem.

So I wonder why there ended up with a `_delete_signal` function. Can you explain it a little bit?

I think this guy's got the same problem. https://github.com/ionelmc/python-redis-lock/issues/58#issuecomment-348712157

**Comment by ionelmc** [comment]
Issue #58 is about fairness - under high load it's possible that locks won't be acquired in the exact chronological order.

After process 2 tries to BLPOP it would loop to SETNX (and might acquire it). What exactly is wrong with that?

https://github.com/ionelmc/python-redis-lock/blob/a30bd138f0f3060cc1f51d6a377b4067fae4dda9/src/redis_lock/__init__.py#L246-L253

**Comment by mt3925** [comment]
When process 2 tries BLPOP, the signal list is empty, so process 2 waits for a timeout, but no one actually uses the lock at this time.

**Comment by ionelmc** [comment]
But does it work or get stuck? Or are you just complaining about efficiency?

**Comment by mt3925** [comment]
If there were no timeouts, BLPOP would really be stuck all the time, so do you think that's normal?

**Comment by ionelmc** [comment]
Hmmmm.... ok it makes sense.

**Comment by rammie** [comment]
Will this change be merged? Happy to make a PR out of @mt3925's work if that would help.

**Comment by ionelmc** [comment]
Yes, I'll make time this week to merge and test the 2 PRs.

**Comment by ionelmc** [comment]
So I've looked a bit through the history, it looks like this situation was introduced in https://github.com/ionelmc/python-redis-lock/issues/47

**Comment by ionelmc** [comment]
Released `v3.4.0`.
