### ISSUE TITLE
Add python 39 as a tox target/add support for python 39.

### ISSUE THREAD

**Issue by SalomonSmeke** [ionelmc/python-redis-lock#79]
As title. Not sure what this would entail, but im happy to do it if this is desirable. Just drop me a y/n comment!

**Comment by ionelmc** [comment]
I usually add that before a release (I reapply that cookiecutter). You can add it if you want to see it in the CI right now I guess, otherwise I'd say it's not really necessary.

**Comment by SalomonSmeke** [comment]
Makes sense!
